services:
  reflex-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: reflex-backend
    ports:
      - "8000:8000"
    networks:
      - reflex-network

  reflex-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: reflex-frontend
    ports:
      - "3000:80"
    depends_on:
      - reflex-backend
    networks:
      - reflex-network

networks:
  reflex-network:
    driver: bridge